language: node_js
sudo: false
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  - TEST_SUITE=lint
  - TEST_SUITE=test
script: npm run $TEST_SUITE
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: ux@dbc.dk
  api_key:
    secure: zFEWKIJclkmNRBHhIfhIRoOVcdIEYpevI2vLX8KWPCtH8BWLcHF/iZd+xY0avtTTCPM73Cuxf7CN9BOkf22AFdCnr/sHTqRvhuD4xhiDElWqh60MDEeDf7M/65oWiDFx2AKgkajLOrXyTGXQyN72vkBzTKHpMAgD8yKs6y6Z3qxRB7noBkdRuxFNZZ9fySvAtkt6vRxdGcB9yFes3iJ73yAAFAumDTieZVE5kXhfHKfxCHfRmWwImG9ZZpXCFZyDWWzZAU/a//mo/CI1PcY9TQHdrOYGsMQPodhYtuqOTuK+j5pZpmXHjEcX0yiESkeysesrJq+2cVOLCLu59PyGo8gMx6DJtsydWsUZOJUKcw1fzpt2jvJl7ODn/Q+dE9XoJlmenR/11E+8abxdAngBZS9NY6tkjzwBsIdaPBlICwOl0zORq4wb/iVht7VXKnym94Ry6orYUcy43wm4aW00Kgcy8rkIlJi/xXcCJ+dfWg6XOJX5i7Ce8b7Y9j3km1fzI8FO2aamN+jnk8t5fAhCF8nur1LW74TtfDtg66WGWnhCNz++7ZIAtLATlLePWfi8twvAQLXewsqR9O2hG04udc33A9S2kzshl095DFVMCZBxwwmUD7gN/ZnN1XiZWtxuttDy+qkuGRiI6rL+w+/3YUpAalJtlesyzdbVT2oY37g=
  on:
    tags: false
    branch: master
    repo: DBCDK/dbc-node-logger
